import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AnimatedLayout from "./components/common/AnimatedLayout";
import CustomCursor from "./components/common/CustomCursor";
import ChatlingWidget from "./components/chat/Chatling";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AnimatedLayout>
          {children}
          <ChatlingWidget />
          <CustomCursor />
        </AnimatedLayout>
      </body>
    </html>
  );
}
